//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tag_info
    {
        public int id { get; set; }
        public string tag_name { get; set; }
        public string tag_discription { get; set; }
        public Nullable<int> tag_level { get; set; }
        public string type { get; set; }
        public Nullable<int> dept_id { get; set; }
    }
}
